<html lang="en">
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
    <meta name='description' content='This is where you add your meta description. Make it count.'>
    <meta name='keywords' content='wood, furniture, garden, garden-table, etc.'>
    <meta name='author' content='Juliana Costa'>
    <title>{titulo}</title>
</head>
<body>
    <h3>Olá, {nome}, tudo bem?</h3>
</body>
</html>